# Generated by Django 3.2.5 on 2021-08-16 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyects', '0005_auto_20210808_0144'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['created']},
        ),
    ]
